route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/'


  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

  # The Child route trees.
  # routes:
