global:
  scrape_interval: 1m

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: [prometheus:9090]

  # For Basic system metrics gathering
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # For Docker monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # For MySQL monitoring
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

# remote_write:
#   - url: '<Your Prometheus remote_write endpoint>'
#     basic_auth:
#       username: ''
#       password: ''

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

rule_files:
  - 'rules.yaml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
